# Generated by Django 2.2 on 2019-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190509_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
