# Generated by Django 2.2 on 2019-05-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='api.Ingredient'),
        ),
    ]
