# Generated by Django 2.2 on 2019-05-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190508_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
