# Generated by Django 2.2 on 2019-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190512_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.CharField(choices=[('PREMIUM', 'premium'), ('STANDART', 'standart'), ('STANDART+', 'standart+'), ('FREE', 'free')], default='FREE', max_length=8),
        ),
    ]
