# Generated by Django 2.2.1 on 2019-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190513_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='foods',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(to='api.Food'),
        ),
    ]
