# Generated by Django 2.2.1 on 2019-05-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190513_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='foods',
        ),
    ]
