# Generated by Django 2.2.1 on 2019-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_ingredient_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='foods',
            field=models.ManyToManyField(to='api.Food'),
        ),
    ]
