# Generated by Django 2.2.1 on 2019-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ingredient_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(to='api.Ingredient'),
        ),
    ]
