# Generated by Django 2.2.1 on 2019-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190513_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='sender',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='check',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='check',
            name='meals',
        ),
        migrations.AddField(
            model_name='check',
            name='foods',
            field=models.ManyToManyField(to='api.Food'),
        ),
    ]
