# Generated by Django 2.2.1 on 2019-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190514_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='total_price',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
