# Generated by Django 2.2.1 on 2019-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190514_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingr',
            field=models.ManyToManyField(to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='api.Ingredient'),
        ),
    ]
