# Generated by Django 2.2.1 on 2019-05-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190514_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='fo',
            field=models.ManyToManyField(to='api.Food'),
        ),
        migrations.AlterField(
            model_name='check',
            name='foods',
            field=models.ManyToManyField(related_name='food', to='api.Food'),
        ),
    ]
