# Generated by Django 2.2.1 on 2019-05-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190514_0629'),
        ('api', '0015_auto_20190513_2136'),
    ]

    operations = [
    ]
