# Generated by Django 3.1.4 on 2020-12-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20190514_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.CharField(choices=[('PREMIUM', 'premium'), ('STANDART', 'standart'), ('STANDART+', 'standart+'), ('FREE', 'free')], default='FREE', max_length=80),
        ),
    ]
